observation:
  robot:
    root_quat_w:
    root_angvel_b:
    projected_gravity_b:
    joint_pos:
    joint_vel:
    prev_actions:       {steps: 1}
    body_pos_b:         {body_names: [
                          left_hip_pitch_link, right_hip_pitch_link, 
                          left_knee_link, right_knee_link, 
                          left_ankle_roll_link, right_ankle_roll_link, 
                          left_shoulder_roll_link, right_shoulder_roll_link, 
                          left_elbow_link, right_elbow_link, 
                          left_wrist_yaw_link, right_wrist_yaw_link
                        ]} 
  ref_motion_public:
    ref_root_quat_w:
    ref_kp_pos_b:       {body_names: [
                          pelvis,
                          left_hip_pitch_link, right_hip_pitch_link, 
                          left_knee_link, right_knee_link, 
                          left_ankle_roll_link, right_ankle_roll_link, 
                          left_shoulder_roll_link, right_shoulder_roll_link, 
                          left_elbow_link, right_elbow_link, 
                          left_wrist_yaw_link, right_wrist_yaw_link
                        ]}

action:
  action_scaling:
    "(?!(waist_roll_joint|waist_pitch_joint)).*": 0.5

default_joint_pos:
  ".*_hip_pitch_joint": -0.312
  ".*_knee_joint": 0.669
  ".*_ankle_pitch_joint": -0.363
  ".*_elbow_joint": 0.6
  left_shoulder_roll_joint: 0.2
  left_shoulder_pitch_joint: 0.2
  right_shoulder_roll_joint: -0.2
  right_shoulder_pitch_joint: 0.2

stiffness:
  [
    40.179237365722656,
    40.179237365722656,
    40.179237365722656,
    99.09842681884766,
    99.09842681884766,
    28.501245498657227,
    40.179237365722656,
    40.179237365722656,
    28.501245498657227,
    99.09842681884766,
    99.09842681884766,
    14.250622749328613,
    14.250622749328613,
    28.501245498657227,
    28.501245498657227,
    14.250622749328613,
    14.250622749328613,
    28.501245498657227,
    28.501245498657227,
    14.250622749328613,
    14.250622749328613,
    14.250622749328613,
    14.250622749328613,
    14.250622749328613,
    14.250622749328613,
    16.77832794189453,
    16.77832794189453,
    16.77832794189453,
    16.77832794189453
    ]

damping:
  [
    2.557889699935913,
    2.557889699935913,
    2.557889699935913,
    6.308801651000977,
    6.308801651000977,
    1.8144457340240479,
    2.557889699935913,
    2.557889699935913,
    1.8144457340240479,
    6.308801651000977,
    6.308801651000977,
    0.9072228670120239,
    0.9072228670120239,
    1.8144457340240479,
    1.8144457340240479,
    0.9072228670120239,
    0.9072228670120239,
    1.8144457340240479,
    1.8144457340240479,
    0.9072228670120239,
    0.9072228670120239,
    0.9072228670120239,
    0.9072228670120239,
    0.9072228670120239,
    0.9072228670120239,
    1.0681414604187012,
    1.0681414604187012,
    1.0681414604187012,
    1.0681414604187012
    ]